name: Deploy frontend to Firebase Hosting on merge
"on":
  push:
    paths:
      - frontend
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        id: vars
        run: echo ::set-output name=pushed_branch::${GITHUB_REF#refs/*/}
      - name: Git checkout
        run: |
          git clone -b ${{ steps.vars.outputs.pushed_branch }} --filter=blob:none --no-checkout --depth 2 --sparse https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git sparse-checkout add frontend
          git checkout ${GITHUB_SHA}
      - name: Dependency Install and Build
        working-directory: ./frontend
        run: ls & npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ICHIREN_SHUFFLE }}"
          channelId: live
          projectId: ichiren-shuffle
          entryPoint: ./frontend
